### PR TITLE
Rebuild hand_over feature and tellrawItem() function

### PR DESCRIPTION
**Pull request by ZZZank**
This PR targets at modernize feature::hand_over_your_items and function::tellrawItem()
### For users
- Items with custom name can get their name displayed properly. 
Let's take a stone that's renamed to `Rock` for example. It will now display `Rock` instead of `Stone` .

### For developers
In hand_over_your_items feature: 
- lang entries for localization are simplified into 2 entries(was 4) , and provides `%s` placeholders
- messages processing are reorganized to be clearer

In tellrawItem() function: 
- move from string concat to "translate":"xxx %s xxx". this makes the overall structure clearer
- auto detection for custom name
- variable re-naming and manual formatting
- important: returned entry parts are now bundled in a single structure. This avoids wrongly consuming `%s` or other placeholder

## Test
Sender Message && Receiver Message:
This image shows what will happen when handling sender/receiver, original/custom name, and different languages. 
image

Older image, not valid now:
This is done by manually disabling fakeplayer logic, which should not affect anything. Screenshots below.
image

### CODE REVIEW

**Comment by Krutoy242** [comment]
Looks very interesting! I will take closer look later.

**Comment by Krutoy242** [comment]
1. Does `item.displayName` works well when server and client locales is different? For example, if server running on en_us and client ch_zn, will client show correct Chinese translation of item name?

2. Please change amount of items to be *in front* of item icon, same as it was before

3. I just discovered recently, that instead of `{"text":""}` you can use bare `""`, since tellraw command can handle simple text. If you gonna make changes, please change that too.

4. Please rename `event` back to `e` since its conventional for all my own code to have short letter `e` for event everywhere.

5. Why are you moved IPlayer instance check down? Isnt if you cast `var target as IPlayer = event.target;` without check class instance, it will produce runtime error? For example, if player right-click entity, it would say `Cant cast IEntity to IPlayer`.

**Comment by ZZZank** [comment]
> 1. Does `item.displayName` works well when server and client locales is different? For example, if server running on en_us and client ch_zn, will client show correct Chinese translation of item name?

I make some more changes, and now it can handle localizations properly, with a bonus: support for custom name!
> 2. Please change amount of items to be _in front_ of item icon, same as it was before
> 3. I just discovered recently, that instead of `{"text":""}` you can use bare `""`, since tellraw command can handle simple text. If you gonna make changes, please change that too.
> 4. Please rename `event` back to `e` since its conventional for all my own code to have short letter `e` for event everywhere.

Done now
> 5. Why are you moved IPlayer instance check down? Isnt if you cast `var target as IPlayer = event.target;` without check class instance, it will produce runtime error? For example, if player right-click entity, it would say `Cant cast IEntity to IPlayer`.

It was intended for reducing variable accesing, but yes, this will causes error. Fixed!

**Comment by Krutoy242** [comment]
Thank you for changes and for additional custom name check!
I have one more question:

Why do you using `item.definition.name` instead of `item.name`? Isnt in your implementation, items with different meta will always output default meta item name? For example, `Granite`, `Diorite` and `Andesite` will always be called `Stone`.

**Comment by ZZZank** [comment]
I use `.definition.name` because I'm not sure about what `item.name` actually means, the CraftTweaker docs give me more confusion than answer on this. 
But your question looks very reasonable, I will swtich to `.name` .

**Comment by Krutoy242** [comment]
Nice improvements! I think this is first time someone helped me with utility functions.

**Pull request merged**
