### PR TITLE
zh_cn localizations for CoT related entries

### PR DESCRIPTION
**Pull request by ZZZank**
This PR includes full translations of entries in `resources/contenttweaker/lang/` , contents including: 

- custom CoT blocks/items/fluids
- renaming for existing blocks
- custom Tcon traits
- tooltips
- chat messages
- recipe names in JEI

There are several untranslated entries, because they are either unused, or should be shown as-is.

### CODE REVIEW

**Comment by Krutoy242** [comment]
Thank you! Gonna merge soon.

**Comment by ZZZank** [comment]
> Thank you! Gonna merge soon.

I think this PR will need some time before being ready for merging, because I want to test my translation in-game to ensure quality.

**Comment by ZZZank** [comment]
Done!
I reviewed this in-game for about 3 times, it should be good enough now.

**Comment by Krutoy242** [comment]
Are you present in E2E-E discord? If you do, I want to give you "contributor" role.

**Comment by ZZZank** [comment]
No, sadly. I lives in China mainland, so I'm unable to access Discord, unless I use some legally risky methods.

**Comment by Krutoy242** [comment]
Gotcha!

**Pull request merged**
