### PR TITLE
Updated schematics

### PR DESCRIPTION
**Pull request by Srdjan-V**
This schematic was also wrong.
If there are anymore broken or missing schematics you can ping me.

### CODE REVIEW

**Comment by Krutoy242** [comment]
Thanks, I would merge that.

There is broken schematics - Modular machines. They all using old single controller, but right now there is mod that makes separate controllers for each machine.

Also, schematics for Scrap Factory is missed.

**Comment by Srdjan-V** [comment]
Sure will make that you can expect it to be done in a day or two.
Do you want me to add it to this pr, or make a new one?

**Comment by Krutoy242** [comment]
> Do you want me to add it to this pr, or make a new one?

Add into this one.

**Comment by Srdjan-V** [comment]
So i made all the schematics for the Enigmatica Machines but i now discovered that they cant be rotated, this is the console log:
_[Client thread/ERROR] [schematica]: 'modularcontroller:advanced_thermionic_fabricator_controller' cannot be rotated around 'up'_

I did test it without the controller its working fine, so my question is what block do you want for the schematic to replace the controller, if at all
Btw i used sky stone bricks for the inputs and outputs on most machines (except for the Arcane Crafting Engine, since it has quite a dark texture), since they can be placed how the player wants
image

**Comment by Krutoy242** [comment]
> they cant be rotated

Seems like this is issue with **Modular Controller** mod. I would be glad if you create issue on this mod issues. I will create issue myself if you don't through.

Please do not use sky stone in structure. Machines should be recognised as is when you place them.
Setup inputs on left and outputs on right.

**Comment by Srdjan-V** [comment]
> I would be glad if you create issue on this mod issues

[ModularController #7](https://github.com/ProjectHDS/ModularController/issues/7)

>Please do not use sky stone in structure

Ok, i will update them no problem

**Comment by Krutoy242** [comment]
Thank you!

**Comment by Srdjan-V** [comment]
This can now be merged
>Setup inputs on left and outputs on right

Did that + added  solid and glass variants, and used the correct capacity for each, for example Advanced Thermionic Fabricator takes  12.000 mb to make a Machine frame so i used a fluid input of 20.000 mb.

**Comment by Krutoy242** [comment]
Great! Thanks!

**Pull request merged**
