### PR TITLE
add textures for demon/enchanted/evil metal

### PR DESCRIPTION
**Pull request by git-confused**
A mod incompatibility prevents extrautils2 from using its dynamically created molten metal textures. This provides imitations of the original textures to be used instead.

### CODE REVIEW

**Comment by Krutoy242** [comment]
I don't get what this fixes. I never have problems with XU textures.
Can you attach screenshots of the problem?

**Comment by Krutoy242** [comment]
I cannot reproduce it. How this happens to you?
image

**Comment by Krutoy242** [comment]
Does this happen on every MC run?
I suspect that its happen only after resource reloading with `F3+R`

**Comment by git-confused** [comment]
I've noticed it a few times when browsing through jei recipes, but I wouldn't notice if it worked sometimes. For the screenshot, I didn't use f3+r or load any resource packs, just loaded the game and made a superflat.

**Pull request closed without merging**
