### PR TITLE
Default controls menu to fit screen

### PR DESCRIPTION
**Pull request by freopt**

### CODE REVIEW

**Comment by Krutoy242** [comment]
Could you provide screenshot of "before" and "after"? I cant understand where this change go.

**Comment by freopt** [comment]
When set to auto/max GUI scale, before:
image
After:
image

text doesn't go off screen anymore

**Comment by Krutoy242** [comment]
I could merge this, but, why you closed this PR?

**Comment by Krutoy242** [comment]
(Oh, I see, another PR)

**Comment by freopt** [comment]
IDK why it didn't add to the other PR

**Pull request merged**
