### PR TITLE
🦯Thaumcraft quest tab rework

### PR DESCRIPTION
**Pull request by TabakaSIM**
> Thaumcraft quest tab rework (does not have translation)

> Buffed Impetus cost in Terraformer

> Changed following moddifiers:
>- dimension modifier 1.75positive/0.75negative (was 1.5;1.25/1.0)
>- elemental modifier 2.5positive/0.5negative (was 1.75/0.75)
>- experience modifier cap increased too 1000lvl (was 100)

### CODE REVIEW

**Comment by Krutoy242** [comment]
Also, please attach some screenshot of your changes - whole TC chapter and best quest desc by your opinion.

**Comment by TabakaSIM** [comment]
Screenshot_20230719_172159
Screenshot_20230719_172256

**Comment by Krutoy242** [comment]
Great! Thank you!

**Comment by Krutoy242** [comment]
Im going to forest tent camp next week, so i would merge it only after my vacation 😔

**Pull request merged**
