### PR TITLE
Added Skyblock chapter for the Patchouli E2E-E book

### PR DESCRIPTION
**Pull request by dyniozaur**
It's quite rich, should work.

### CODE REVIEW

**Comment by Krutoy242** [comment]
I made some change examples, rebased PR and force-pushed it.
Maybe my working with GIT can be little awkward right now.

**Comment by MironTheDev** [comment]
Btw i recommend add sky resources 4

**Comment by Krutoy242** [comment]
> Btw i recommend add sky resources 4

Thanks for recommendation.
I think E2E-E already have lot of resource generation options so we don't need SR

**Comment by Krutoy242** [comment]
Any updates?

**Comment by Krutoy242** [comment]
Since no progress has been made in almost half a year, I will close this Pull Request. Open it whenever you want, if there are any changes.

Like I said before, I don't want to add tips as they are now and they need changes.

**Pull request closed without merging**
