### PR TITLE
Add Tomdodd's Reactor designs to Schematica.

### PR DESCRIPTION
**Pull request by Nonname123C**
Built and tested in Creative but it should work in Survival. Added Redstone blocks to Neutron sources, Infinite Water Sources and Fluid Trash Bin so it will work out of the box.

### CODE REVIEW

**Comment by Krutoy242** [comment]
I tested Irradiator for now and it looks almost perfect! I like that there is no wrong blocks and structure is faced to user.
But, i would like to ask for a fix or two:

1. It feels like this water source cant keep up with reactor consumption. I see how amount of water slowly run down, so eventually this will lead to casing overhead. Please replace it with higher level. If you not sure what exact level of `Infinity Water Source` you should use, just place biggest one - this setup only intended for creative world tests. In real scenarios players will place something else.
  https://github.com/user-attachments/assets/dc245e66-0c1f-40d2-a8f1-2f91648f7f76

2. Rename burners to `LE~ Burner` and `HE~ Burner`. This breeding reactors supposed to be used with ANY kinds of highly-enriched and low-enriched fuels, not only `Cf-249`.

**Comment by Nonname123C** [comment]
should we further clarify them by renaming as `Low-Enriched Fuel Burner` and `High-Enriched Fuel Burner` for average players?

**Comment by Krutoy242** [comment]
Probably this would be better, yes.

**Comment by Nonname123C** [comment]
Updated the Schematics, now everything should have Dense Infinite Water sources and the Burners have been renamed

**Comment by Krutoy242** [comment]
I will remove old reactor schematics and merge the PR after

**Pull request merged**
