### PR TITLE
skyblocktest1

### PR DESCRIPTION
**Pull request by LisonaZ**
Added Quests to the Skyblock Chapter

### CODE REVIEW

**Comment by Krutoy242** [comment]
You accidentally undo all my changes in last release. You must fix that. Check all changed files and only keep changes you actually made. For example, you undoed my removal of Coils in Advanced Rocketry chapter.

**Comment by LisonaZ** [comment]
I'm sorry, I haven't fully figured out how to operate it yet. I'll resubmit once I've learned

**Comment by Krutoy242** [comment]
> I'm sorry, I haven't fully figured out how to operate it yet. I'll resubmit once I've learned

Its ok! Right now your PR have no changes at all 😁
You removed all of them, even ones you did yourself.

**Comment by Krutoy242** [comment]
You still have changes chat undo (revert) my own changes in modpack. Please take a look at each file and fix it:

- config\ftbquests\normal\chapters\4f65de69\14611430.snbt
- config\ftbquests\normal\chapters\4f65de69\4fc58528.snbt
- config\ftbquests\normal\chapters\4f65de69\67d93373.snbt
- config\ftbquests\normal\chapters\4f65de69\6861a52d.snbt
- config\ftbquests\normal\chapters\4f65de69\95bcbfad.snbt
- config\ftbquests\normal\chapters\4f65de69\ce6ae148.snbt
- config\ftbquests\normal\chapters\4f65de69\f968d750.snbt
- config\ftbquests\normal\chapters\4f65de69\fc892a79.snbt

Also, please do not propose empty changes. Many files in Getting Started chapter are proposed for a change, but actually, only line endings was changed. Please add changes to PR only if there is actual changes, not just line ending format (`\r\n`).

**Comment by Krutoy242** [comment]
Why did you closed this PR?

**Comment by LisonaZ** [comment]
The previous branch left me somewhat confused due to my foolish actions. Without changing the original quest, I added a new chapter. I created a new branch and resubmitted the pull request.

**Pull request closed without merging**
