### PR TITLE
zh_cn localization fix

### PR DESCRIPTION
**Pull request by ZZZank**
- fix localizations in `scripts/do/hand_over_your_items.zs`
- add some localizations for CoT fluid materials
- correction on `zh_cn.lang` filename

Chinese and English have different word orders, that's why I use an extra comma. The comma is not a bug. It's a feature. 
Maybe we can use placeholders like '%s' for better formatted result. 
And, about those localizations bundled in zs files, is it possible to split them to a seperate xxx.lang file?

### CODE REVIEW

**Comment by Krutoy242** [comment]
Thank you for the fixes!

I'm kinda new in this language shenanigans, so maybe later I could move to %s tricks, but now only that way.

Why you want to separate them in .lang files? I want to bundle this 
.zs files as "customisation" for CurseForge or submodule for git, that why I'm trying to keep everything in one folder.

And lastly, I need help with portal spread translation too. Would you like to help me with it?

**Comment by ZZZank** [comment]
> Why you want to separate them in .lang files?

Because that's usually a 'standard' way of localization, which can help with locating untranslated contents. But you're also right, being in one folder is good for management. 

> I need help with portal spread translation too. Would you like to help me with it?

Sure!

**Comment by Krutoy242** [comment]
How good your Chinese is? I mean, can I trust quality of this translations?

**Comment by ZZZank** [comment]
> How good your Chinese is? I mean, can I trust quality of this translations?

My mother tongue is Chinese. And based on my own experience, I can say my translation is in 'good, occationally awesome' level. 
But it will still be great to find someone else to verify these translations. It can be helpful for the quality of translations. 

And I that's all contents for this PR, there are still many untranslated entries in resources/contenttweaker/lang/zh_cn.lang , but I think it should be in another PR, instead of being mixed with these fixes.

**Comment by Krutoy242** [comment]
Ok, sounds good for me! Thanks for help.

Also, if you want to drive really deep into CN translation, I could prepare all modpack strings for Chinese translation, but you would need lot of time to translate everything.

**Pull request merged**
