### PR TITLE
fix Player Simulator item dupe

### PR DESCRIPTION
**Pull request by ZZZank**
## Summary
see #280. This PR fixes that. 

## Technical details
I use `e.player.fake` to determine if a player is FakePlayer. If is, simply skip `hand over your items` processing. 

~~Thankfully, IntgDyn gives the name that its FakePlayer uses : `[IntegratedTunnels]` .~~
~~references: https://github.com/CyclopsMC/IntegratedTunnels/blob/800584c534a7c6a00cd3bc8bc3cf8cb33d7d529e/src/main/java/org/cyclops/integratedtunnels/core/ExtendedFakePlayer.java#L16C2-L16C2~~

As for Cyclic and ExtraUtilities2, their Player Simulator does not support sneaking, so no need to handle that. 

## Deprecated Alternative Methods
-  use `isFake()` function

`IPlayer` in 1.12 does not actually provides this method(getter) . While it's true that there is a global function call `isFake()` that accepts `crafttweaker.player.IPlayer` as arg , it does not work well with `IntegratedTunnels` , outputing errors like this: 
```
[SERVER_STARTED][SERVER][ERROR] Truncated class file
java.lang.ClassFormatError: Truncated class file
   ...
```

- use UUID comparision 

not usable for unknown reason

- use name comparision 

use `e.player.fake` instead, for better mod compability

### CODE REVIEW

**Comment by Krutoy242** [comment]
Isn't `IPlayer` have `isFake`getter? I can just check any fake player.

**Comment by ZZZank** [comment]
> Isn't `IPlayer` have `isFake`getter? 

Do they? I didn't find such a method on [1.12 wiki](https://docs.blamejared.com/1.12/en/Vanilla/Players/IPlayer) , it seems to be modern version only([like 1.16](https://docs.blamejared.com/1.16/en/vanilla/api/entity/MCPlayerEntity))

**Comment by ZZZank** [comment]
I just tested `isFake()` on my instance, it does not works (related error is sorted into "Failed Alternative Methods" part) , and so did UUID comparision. So I switch to name comparsion for fixing this.

**Comment by Krutoy242** [comment]
`if(player.fake)` is ZenUtils mod field, try it https://github.com/friendlyhj/ZenUtils/blob/7b491fc8260c64babefca1436b571dbce34bc7e0/src/main/java/youyihj/zenutils/api/player/ZenUtilsPlayer.java#L58-L62

**Comment by ZZZank** [comment]
> `if(player.fake)` is ZenUtils mod field, try it 

Cool feature! Switched.

**Comment by Krutoy242** [comment]
What does this syntax means?
```
e.player.fake`e.player.fake`
```
Especially, part incased in `

**Comment by ZZZank** [comment]
It's a bug, because my IDE submits unsaved changes.

**Pull request merged**
