### PR TITLE
Add Arboreal Extractor to JEI

### PR DESCRIPTION
**Pull request by icemoss**

### CODE REVIEW

**Comment by Krutoy242** [comment]
You accidentally removed langs for two coins in Ru and Ch files. Please fix that.

**Comment by icemoss** [comment]
I must have done that by accident, but it seems like the langs were already removed in the English version https://github.com/Krutoy242/Enigmatica2Expert-Extended/pull/303

**Comment by Krutoy242** [comment]
Ok, i could keep that, but next time its better to follow rule `one feature - one PR`. Removing lang files for coins considered as another feature.

**Comment by icemoss** [comment]
alright, I'll try document changes further

**Comment by Krutoy242** [comment]
Please attach any screenshot that show resulting page - I want to add it to changelogs

**Comment by icemoss** [comment]
arboreal

**Comment by Krutoy242** [comment]
Thanks!

**Pull request merged**
