### PR TITLE
Fix TC quest descriptions

### PR DESCRIPTION
**Pull request by ClassixX**
Some grammar edits, probably still overlooked some typos

### CODE REVIEW

**Comment by Krutoy242** [comment]
Seems like you messed with branches. I can't merge it.

**Comment by ClassixX** [comment]
Github showed me some conflicts that I fixed, does it work now?

**Comment by Krutoy242** [comment]
image
Why did you added empty line here?

**Comment by Krutoy242** [comment]
Ok, thanks for more fixes!

**Pull request merged**
