### PR TITLE
Rework Thaumic Wonders

### PR DESCRIPTION
**Pull request by XuaTheGrate**
Catalyzation Chamber stones: can now be enchanted with Mending and Unbreaking 1-3

- Alchemist Stone: Added the remainder of the native clusters from JAOPCA
- Alienist Stone: Ores will convert into Crystal Shards from JAOPCA instead of Eldritch Clusters
- Transmuter Stone: Added new conversions:
- - Copper <-> Tin
- - Silver <-> Lead
- - Gold <-> Iron
- - Cobalt <-> Ardite
- - Starmetal <-> Draconium
- - Platinum <-> Iridium
- - Aluminum <-> Titanium
- - Uranium <-> Thorium
- - Xorcyte <-> Aquamarine
- - Diamond <-> Sapphire
- - Emerald <-> Peridot
- - Redstone <-> Ruby
- - Certus Quartz <-> Charged Certus Quartz
- - Dilithium <-> Dimensional Shard
- - Coal <-> Bitumen
- Conversions can be done with dusts, blocks, ingots, gems and the raw ores.

Meaty Orb: can now be activated with a redstone signal (if it has enough Essentia)

Left to do:
- [x] Fix anvil not working with the catalyzation chamber stones
- [ ] Add JEI tab for the catalyzation chamber
- [ ] Attempt at automation for moving the stones in and out of the chamber

### CODE REVIEW

**Comment by Krutoy242** [comment]
If it's not ready to merge, mark it as "draft".
Also, what is this .gitempty files?

**Comment by XuaTheGrate** [comment]
The empty files were just there so I could upload files into certain folders easier.

**Comment by Krutoy242** [comment]
I don't understand. If this files have no meaning for modpack, they should be removed.

**Comment by Krutoy242** [comment]
Thanks!

**Comment by XuaTheGrate** [comment]
Anvil enchantments have been fixed!

**Pull request merged**
